# Basic Python

## 1. Split this string

In [1]:
s = "Hi there Sam!"

In [2]:
s.split()

['Hi', 'there', 'Sam!']

*`italicized text`*## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [3]:
planet = "Earth"
diameter = 12742

In [4]:
print("The diameter of {} is {} kilometers.".format(planet,diameter))


The diameter of Earth is 12742 kilometers.


## 3. In this nest dictionary grab the word "hello"

In [5]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [6]:
d['k1'][3]['tricky'][3]['target'][3]

'hello'

# Numpy

In [7]:
import numpy as np


## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [8]:
import numpy as np
array=np.zeros(10)
print("An array of 10 zeros:")
print(array)




An array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [9]:

import numpy as np
array=np.ones(10)*5
print("An array of 10 fives:")
print(array)

An array of 10 fives:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


## 5. Create an array of all the even integers from 20 to 35

In [10]:
import numpy as np
array=np.arange(20,36,2)
print("Array of all the even integers from 20 to 35")
print(array) 

Array of all the even integers from 20 to 35
[20 22 24 26 28 30 32 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [11]:
import numpy as np
Z = np.arange(9).reshape(3,3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 7. Concatinate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [12]:
import numpy as np
  
arr1 = np.array([[1,2,3]])
arr2 = np.array([[4,5,6]])
  
cde = np.concatenate((arr1, arr2), axis = 0)  
print (cde)


  


[[1 2 3]
 [4 5 6]]


# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [22]:
pip install pandas
import pandas as pd

SyntaxError: invalid syntax (<ipython-input-22-c5f35f616dad>, line 1)

In [ ]:
import pandas as pd
  
data = [['tom', 10], ['nick', 15], ['juli', 14]]
  
df = pd.DataFrame(data, columns=['Name', 'Age'])
  
df

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [ ]:
import datetime
import pandas as pd
 
# initializing date
test_date = datetime.datetime.strptime("01-6-2023", "%d-%m-%Y")
 
# initializing K
K = 10
 
date_generated = pd.date_range(test_date, periods=K)
print(date_generated.strftime("%d-%m-%Y"))

## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [ ]:
import pandas as pd
lst = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]] 
  
# creating df object with columns specified    
df = pd.DataFrame(lst, columns =['Tag', 'number']) 
print(df )